### ISSUE TITLE
Segmentation Fault while running vanilla-installer

### ISSUE THREAD

**Issue by andrew-stclair** [Vanilla-OS/vanilla-installer#276] opened 2023-09-06 11:52 UTC
Hello,

I am getting a Segmentation Fault when running the installer on my Asus VivoBook 15 Model F512J.

This does not seem to be linked with any user action, as it happens consistently after a certain period of time, if I've gone through some pages or just left it there after clicking install. This can happen anywhere between seconds and minutes.

one thing i discovered tough while trying to figure out timing etc.., may be unrelated, is when leaving the installer on the first page with the install/recovery options for 2 minutes, It'll give me a `free(): corrupted unsorted chunks` `Aborted` error. Though i only got this once.

I did get a core dump from one of the Segmentation Faults after following these steps:

- Push `alt` and `f2` on the keyboard and enter `xterm` in the prompt
- In xterm, run `ulimit -c unlimited`, then run `vanilla-installer`
- let it crash with a Segmentation Fault
- mount an extra usb drive and copy the dump to it

[core.zip](https://github.com/Vanilla-OS/vanilla-installer/files/12536950/core.zip)

Installer version is from the most recent alpha release from the 30th of August.

Hope it's useful.

**Comment by mirkobrombin** [comment] 2023-09-13 22:02
Duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/271 but I'll keep this since has more details. Thanks for reporting.

**Closed** 2023-09-20 20:11 UTC
Labels: bug
