### ISSUE TITLE
[Orchid] wrong keyboard layout at boot time : hard to type the password to decrypt the disk

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/vanilla-installer#262] opened 2023-08-28 19:51 UTC
### Issue Description

At first reboot (after install), it's hard to type the password to decrypt the hdd as the keyboard layout is set to us by default.

### Steps to Reproduce

- At installation time, I chose a keyboard layout (not us) and I decided to encrypt my hdd.
- Installation succeeded and the vm rebooted.
- At reboot it ask for my password to decrypt my hdd.
- The keyboard layout is us so it makes it difficult to type my password

### On what version of Vanilla OS this happens?

Unreleased

**Comment by ludvigng** [comment] 2023-09-01 11:03
As a temporary work-around you could try appending something like `rd.vconsole.keymap=` followed by your keymap to the kernel command line. Fedora Silverblue has a similar issue where you need to rebuild the initramfs for it to pick up the new keyboard layout: https://github.com/fedora-silverblue/issue-tracker/issues/3

**Comment by Thatoo** [comment] 2023-09-19 16:02
issue still true with the image #77 | 17/09/2023

**Comment by Thatoo** [comment] 2024-01-08 17:19
> As a temporary work-around you could try appending something like `rd.vconsole.keymap=` followed by your keymap to the kernel command line. Fedora Silverblue has a similar issue where you need to rebuild the initramfs for it to pick up the new keyboard layout: [fedora-silverblue/issue-tracker#3](https://github.com/fedora-silverblue/issue-tracker/issues/3)

@ludvigng would you modify the grub file in /etc/default ? Here's how it is composed after a fresh install. How would you modify it to be able to use let's say a french keyboard?

![image](https://github.com/Vanilla-OS/vanilla-installer/assets/464782/b2f5a302-2f61-4e77-ac47-8e6f932076fd)

**Comment by Thatoo** [comment] 2024-01-08 17:22
In Debian 11, to change this option, we should go to Settings > Country and languages > Connexion screen and then choose the keyboard we want and put it on top : 

![image](https://github.com/Vanilla-OS/vanilla-installer/assets/464782/38d05955-4bb0-49a7-aaec-a9c6c5ded94e)

**Comment by taukakao** [comment] 2024-01-12 19:55
duplicate of https://github.com/Vanilla-OS/Albius/issues/40

**Closed by taukakao** 2024-01-12 19:55 UTC
Labels: bug, duplicate, triage
