### ISSUE TITLE
Orchid build 130 installer crashes

### ISSUE THREAD

**Issue by OzyOzyOzyOzyOzy** [Vanilla-OS/vanilla-installer#391] opened 2024-07-13 19:44 UTC
### Issue Description

After starting the installation point, the installer (the actual program within the live usb) will crash at random points during install. The installer has crashed at the following points:
*Immediately upon loading
*After selecting a time zone
*After selecting a keyboard layout
*After selecting a language
*After connecting to wifi
*After starting the partitioning process
*During time zone setting during the installation process

These crashes happen at random points and times.

### Steps to Reproduce

1. Flash Vanilla OS 2 (orchid) to usb using balena etcher
2. Begin installation process
3. Crash will occur at random points and at random times

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

I also flashing the iso using dd and GNOME Disks, with the same results.

**Comment by rockozzz** [comment] 2024-07-16 20:04
> could you connect to wifi from the top right corner istead of the dialog in the installer and try again?

I had the same issue as mentioned by [OzyOzyOzyOzyOzy] and your workaround fixed my issue.

Thanks a lot

**Comment by taukakao** [comment] 2024-07-28 13:16
I'm guessing this is a duplicate of #301 
Reopen this if that is not correct.

**Closed by taukakao** 2024-07-28 13:16 UTC
Labels: bug, triage
