### ISSUE TITLE
Vanilla OS 2; GNOME shouldn't automatically suspend during install

### ISSUE THREAD

**Issue by totaltommygun** [Vanilla-OS/vanilla-installer#387] opened 2024-07-09 05:57 UTC
GNOME has "Automatic Suspend" on by default during the installer, which can cause issues if left unattended

![6d9836be-ac27-4e7e-8e12-8a8115032039](https://github.com/Vanilla-OS/vanilla-installer/assets/154575581/552a6a07-562e-46a6-90fa-13319fcc2a5c)

**Comment by taukakao** [comment] 2024-07-09 11:23
It isn't enabled for me. 
What version of the iso are you using?

**Comment by tristann21** [comment] 2024-07-09 17:37
> It isn't enabled for me. What version of the iso are you using?

Latest version of Orchid at the time of writing the issue. Could it somehow be ventoy?

**Comment by taukakao** [comment] 2024-07-09 20:01
I doubt it. Ventoy should just control the boot process. 
If there's nothing else then it could be worth a test tho.

**Comment by acerspyro** [comment] 2024-12-02 05:20
Duplicate of #289

**Comment by taukakao** [comment] 2024-12-02 05:28
Yup

**Closed by taukakao** 2024-12-02 05:28 UTC
