### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by minima1cha0s** [Vanilla-OS/vanilla-installer#274] opened 2023-09-04 06:28 UTC
During the installatin moving the mouse outside the installer window to the right changes the mouse cursor to a right pointing arrow which does not reset.

VanillaOS-2-testing.20230829 in boxes

**Comment by acerspyro** [comment] 2024-12-02 05:18
Cannot reproduce, is this still an issue?

**Comment by mirkobrombin** [comment] 2024-12-02 08:16
I was never able to replicate

**Comment by taukakao** [comment] 2024-12-02 13:52
I'm gonna close it. It can be reopened if it's still an issue.

**Closed by taukakao** 2024-12-02 13:52 UTC
