### ISSUE TITLE
Can't boot after sucessful install

### ISSUE THREAD

**Issue by ShadowCreator** [Vanilla-OS/vanilla-installer#363] opened 2024-03-08 01:07 UTC
I've installed the latest iso successfully on another computer with automatic partitioning and have been using it for a fortnight. But on my laptop after installation and rebooting, I get errors saying:

`Failed to open \EFI\BOOT\? - Invalid Parameter
Failed to load image ??: Invalid Parameter
start_image() returned Invalid Parameter, falling back to default loader`

Then if the usb is still plugged in: it goes to the iso install boot menu
If the usb isn't: it goes to my uefi settings as if my boot list has been wiped (might be related to issue #350)

Trying to reinstall also causes a strange error, after pressing confirm install gives an error in the state "Setup 1/20 label" which panics as partition 4 on /dev/nvme0n1 has already been written. However starting the installer again lets it install without error

**Comment by taukakao** [comment] 2024-03-08 13:14
How is the boot entry called in your UEFI settings?

**Comment by ShadowCreator** [comment] 2024-03-08 23:11
There's no boot menu entries anymore, not even for Vanilla OS. Similar to #350

**Comment by taukakao** [comment] 2024-06-03 08:55
Probably duplicate of #380

**Closed by taukakao** 2024-06-03 08:55 UTC
