### ISSUE TITLE
[Feature Request] Install on USB Stick (Portable Installation)

### ISSUE THREAD

**Issue by trymeouteh** [Vanilla-OS/vanilla-installer#354] opened 2024-02-09 21:01 UTC
Please add an option to flash VanillaOS onto a portable USB drive which will support full disk encryption, and allow for persistance storage.

**Comment by taukakao** [comment] 2024-02-10 18:04
duplicate of https://github.com/Vanilla-OS/vanilla-installer/issues/348

**Closed by taukakao** 2024-02-10 18:04 UTC
