### ISSUE TITLE
Manual partitioning not possible

### ISSUE THREAD

**Issue by merj1928** [Vanilla-OS/vanilla-installer#87] opened 2022-12-31 06:38 UTC
When I try to split the disk manually, the switch does not activate. Thus I can not partition the hard disk

**Comment by kbdharun** [comment] 2022-12-31 06:42
Thanks for the report it is a duplicate of #86

**Comment by mirkobrombin** [comment] 2022-12-31 07:38
duplicate of #86

**Closed by mirkobrombin** 2022-12-31 07:38 UTC
